version: '3'

services:
  mongo:
    container_name: mongo-service
    image: mongo:4.0.13-xenial
    environment:
      MONGO_INITDB_DATABASE: geoCovid
      MONGO_INITDB_ROOT_USERNAME: geo_covid_root
      MONGO_INITDB_ROOT_PASSWORD: senha.123
      TZ: America/Fortaleza
    ports:
      - "27017:27017"
    volumes:
      - db-data-mongodb:/data/db
      - ./database/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    networks:
      - datanodes-network

  mongo-express:
    container_name: mongo-express-web
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: senha.123
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: geo_covid_root
      ME_CONFIG_MONGODB_ADMINPASSWORD: geo.covid.123
    depends_on:
      - mongo
    networks:
      - datanodes-network

  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - datanodes-network

volumes:
  db-data:
  db-data-mongodb:

networks:
  datanodes-network:
    driver: bridge
