# Generated by Django 3.0.2 on 2020-01-11 23:12

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='A short name that will be used to uniquely \t\tidentify you on the platform.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[\\w.@+-]+$'), 'Enter a valid username. This value must contain only letters, numbers, and the characters: @/./+/-/_ .', 'invalid')], verbose_name='Username'),
        ),
    ]
